package com.kanghoshin.lis.dao;

import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;

import com.kanghoshin.lis.dto.prescriptionorder.CreatePrescriptionOrderDto;
import com.kanghoshin.lis.dto.prescriptionorder.ReadFullTestPrescriptionOrderListDto;
import com.kanghoshin.lis.vo.prescriptionorder.FullTestPrescriptionOrderVo;

@Mapper
public interface PrescriptionOrderMapper {

	@Insert("<script> "
			+ "INSERT INTO prescription_order VALUES "
			+ "<foreach collection='createPrescriptionOrderDto' item='item' separator=', '> "
			+ "( "
			+ "null, "
			+ "#{item.consultationNo}, "
			+ "#{item.prescriptionCode}, "
			+ "null "
			+ ") "
			+ "</foreach>"
			+ "</script>")
	int insertList(@Param("createPrescriptionOrderDto")CreatePrescriptionOrderDto[] createPrescriptionOrderDto);
	
	@Select("<script>"
			+ "SELECT * FROM full_test_prescription_order "
			+ "<where> "
			+ "<if test='readFullTestPrescriptionOrderListDto.consultationNoKey != null'> "
			+ "consultation_no like CONCAT('%',#{readFullTestPrescriptionOrderListDto.consultationNoKey},'%') "
			+ "</if> "
			+ "<if test='readFullTestPrescriptionOrderListDto.consultationTimeStart &gt; 0'> "
			+ "AND consultation_time &gt;= #{readFullTestPrescriptionOrderListDto.consultationTimeStart} "
			+ "</if> "
			+ "<if test='readFullTestPrescriptionOrderListDto.consultationTimeEnd &gt; 0'> "
			+ "AND consultation_time &lt;= #{readFullTestPrescriptionOrderListDto.consultationTimeEnd} "
			+ "</if> "
			+ "<if test='readFullTestPrescriptionOrderListDto.consultationReceptionNoKey != null'> "
			+ "AND consultation_reception_no like CONCAT('%',#{readFullTestPrescriptionOrderListDto.consultationReceptionNoKey},'%') "
			+ "</if> "
			+ "<if test='readFullTestPrescriptionOrderListDto.consultationReceptionTimeStart &gt; 0'> "
			+ "AND consultation_reception_time &gt;= #{readFullTestPrescriptionOrderListDto.consultationReceptionTimeStart} "
			+ "</if> "
			+ "<if test='readFullTestPrescriptionOrderListDto.consultationReceptionTimeEnd &gt; 0'> "
			+ "AND consultation_reception_time &lt;= #{readFullTestPrescriptionOrderListDto.consultationReceptionTimeEnd} "
			+ "</if> "
			+ "<if test='readFullTestPrescriptionOrderListDto.staffNoKey != null'> "
			+ "AND staff_no like CONCAT('%',#{readFullTestPrescriptionOrderListDto.staffNoKey},'%') "
			+ "</if> "
			+ "<if test='readFullTestPrescriptionOrderListDto.patientNo > 0'> "
			+ "AND patient_no = #{readFullTestPrescriptionOrderListDto.patientNo} "
			+ "</if> "
			+ "<if test='readFullTestPrescriptionOrderListDto.patientNoKey != null'> "
			+ "AND patient_no like CONCAT('%',#{readFullTestPrescriptionOrderListDto.patientNoKey},'%') "
			+ "</if> "
			+ "<if test='readFullTestPrescriptionOrderListDto.consultationReceptionAppointmentStart &gt; 0'> "
			+ "AND consultation_reception_appointment &gt;= #{readFullTestPrescriptionOrderListDto.consultationReceptionAppointmentStart} "
			+ "</if> "
			+ "<if test='readFullTestPrescriptionOrderListDto.consultationReceptionAppointmentEnd &gt; 0'> "
			+ "AND consultation_reception_appointment &lt;= #{readFullTestPrescriptionOrderListDto.consultationReceptionAppointmentEnd} "
			+ "</if> "
			+ "<if test='readFullTestPrescriptionOrderListDto.prescriptionOrderNoKey != null'> "
			+ "AND prescription_order_no like CONCAT('%',#{readFullTestPrescriptionOrderListDto.prescriptionOrderNoKey},'%') "
			+ "</if> "
			+ "<if test='readFullTestPrescriptionOrderListDto.prescriptionCodeKey != null'> "
			+ "AND prescription_code like CONCAT('%',#{readFullTestPrescriptionOrderListDto.prescriptionCodeKey},'%') "
			+ "</if> "
			+ "<if test='readFullTestPrescriptionOrderListDto.prescriptionOrderTimeStart &gt; 0'> "
			+ "AND prescription_order_time &gt;= #{readFullTestPrescriptionOrderListDto.prescriptionOrderTimeStart} "
			+ "</if> "
			+ "<if test='readFullTestPrescriptionOrderListDto.prescriptionOrderTimeEnd &gt; 0'> "
			+ "AND prescription_order_time &lt;= #{readFullTestPrescriptionOrderListDto.prescriptionOrderTimeEnd} "
			+ "</if> "
			+ "<if test='readFullTestPrescriptionOrderListDto.specimenContainerCodeKey != null'> "
			+ "AND specimen_container_code like CONCAT('%',#{readFullTestPrescriptionOrderListDto.specimenContainerCodeKey},'%') "
			+ "</if> "
			+ "<if test='readFullTestPrescriptionOrderListDto.specimenTypeCodeKey != null'> "
			+ "AND specimen_type_code like CONCAT('%',#{readFullTestPrescriptionOrderListDto.specimenTypeCodeKey},'%') "
			+ "</if> "
			+ "<if test='readFullTestPrescriptionOrderListDto.prescriptionNameKey != null'> "
			+ "AND prescription_name like CONCAT('%',#{readFullTestPrescriptionOrderListDto.prescriptionNameKey},'%') "
			+ "</if> "
			+ "<if test='readFullTestPrescriptionOrderListDto.prescriptionClassificationCodeKey != null'> "
			+ "AND prescription_classification_code like CONCAT('%',#{readFullTestPrescriptionOrderListDto.prescriptionClassificationCodeKey},'%') "
			+ "</if> "
			+ "<if test='readFullTestPrescriptionOrderListDto.prescriptionSlipCodeKey != null'> "
			+ "AND prescription_slip_code like CONCAT('%',#{readFullTestPrescriptionOrderListDto.prescriptionSlipCodeKey},'%') "
			+ "</if> "
			+ "<if test='readFullTestPrescriptionOrderListDto.prescriptionCommentKey != null'> "
			+ "AND prescription_comment like CONCAT('%',#{readFullTestPrescriptionOrderListDto.prescriptionCommentKey},'%') "
			+ "</if> "
			+ "</where> "
			+ "<trim prefix='ORDER BY' prefixOverrides=','> "
			+ "<if test='readFullTestPrescriptionOrderListDto.consultationNoOrder != null'> "
			+ "consultation_no ${readFullTestPrescriptionOrderListDto.consultationNoOrder} "
			+ "</if> "
			+ "<if test='readFullTestPrescriptionOrderListDto.consultationTimeOrder != null'> "
			+ ", consultation_time ${readFullTestPrescriptionOrderListDto.consultationTimeOrder} "
			+ "</if> "
			+ "<if test='readFullTestPrescriptionOrderListDto.consultationReceptionNoOrder != null'> "
			+ ", consultation_reception_no ${readFullTestPrescriptionOrderListDto.consultationReceptionNoOrder} "
			+ "</if> "
			+ "<if test='readFullTestPrescriptionOrderListDto.consultationReceptionTimeOrder != null'> "
			+ ", consultation_reception_time ${readFullTestPrescriptionOrderListDto.consultationReceptionTimeOrder} "
			+ "</if> "
			+ "<if test='readFullTestPrescriptionOrderListDto.staffNoOrder != null'> "
			+ ", staff_no ${readFullTestPrescriptionOrderListDto.staffNoOrder} "
			+ "</if> "
			+ "<if test='readFullTestPrescriptionOrderListDto.patientNoOrder != null'> "
			+ ", patient_no ${readFullTestPrescriptionOrderListDto.patientNoOrder} "
			+ "</if> "
			+ "<if test='readFullTestPrescriptionOrderListDto.consultationReceptionAppointmentOrder != null'> "
			+ ", consultation_reception_appointment ${readFullTestPrescriptionOrderListDto.consultationReceptionAppointmentOrder} "
			+ "</if> "
			+ "<if test='readFullTestPrescriptionOrderListDto.prescriptionOrderNoOrder != null'> "
			+ ", prescription_order_no ${readFullTestPrescriptionOrderListDto.prescriptionOrderNoOrder} "
			+ "</if> "
			+ "<if test='readFullTestPrescriptionOrderListDto.prescriptionCodeOrder != null'> "
			+ ", prescription_code ${readFullTestPrescriptionOrderListDto.prescriptionCodeOrder} "
			+ "</if> "
			+ "<if test='readFullTestPrescriptionOrderListDto.prescriptionOrderTimeOrder != null'> "
			+ ", prescription_order_time ${readFullTestPrescriptionOrderListDto.prescriptionOrderTimeOrder} "
			+ "</if> "
			+ "<if test='readFullTestPrescriptionOrderListDto.specimenContainerCodeOrder != null'> "
			+ ", specimen_container_code ${readFullTestPrescriptionOrderListDto.specimenContainerCodeOrder} "
			+ "</if> "
			+ "<if test='readFullTestPrescriptionOrderListDto.specimenTypeCodeOrder != null'> "
			+ ", specimen_type_code ${readFullTestPrescriptionOrderListDto.specimenTypeCodeOrder} "
			+ "</if> "
			+ "<if test='readFullTestPrescriptionOrderListDto.prescriptionNameOrder != null'> "
			+ ", prescription_name ${readFullTestPrescriptionOrderListDto.prescriptionNameOrder} "
			+ "</if> "
			+ "<if test='readFullTestPrescriptionOrderListDto.prescriptionClassificationCodeOrder != null'> "
			+ ", prescription_classification_code ${readFullTestPrescriptionOrderListDto.prescriptionClassificationCodeOrder} "
			+ "</if> "
			+ "<if test='readFullTestPrescriptionOrderListDto.prescriptionSlipCodeOrder != null'> "
			+ ", prescription_slip_code ${readFullTestPrescriptionOrderListDto.prescriptionSlipCodeOrder} "
			+ "</if> "
			+ "<if test='readFullTestPrescriptionOrderListDto.prescriptionCommentOrder != null'> "
			+ ", prescription_comment ${readFullTestPrescriptionOrderListDto.prescriptionCommentOrder} "
			+ "</if> "
			+ "</trim> "
			+ "limit #{readFullTestPrescriptionOrderListDto.pageStart}, #{readFullTestPrescriptionOrderListDto.pageSize} "
			+ "</script>")
	FullTestPrescriptionOrderVo[] selectFullTestPrescriptionOrder(@Param("readFullTestPrescriptionOrderListDto") ReadFullTestPrescriptionOrderListDto readFullTestPrescriptionOrderListDto);
}
