import React from "react";
import axios from "axios";

export const fetchdata = async () => {
  try {
    const response = {
      patients: [
        { id: 1, title: "강현구" },
        { id: 2, title: "김동신" },
        { id: 3, title: "류호진" },
        { id: 4, title: "금난새" },
        { id: 5, title: "금내리" },
        { id: 6, title: "금노리" },
        { id: 7, title: "금노상" },
        { id: 8, title: "이따사롬" },
        { id: 9, title: "이슬기롬" },
        { id: 10, title: "김나래" },
        { id: 11, title: "김나리" },
        { id: 12, title: "한이랑" },
        { id: 13, title: "한사랑" },
        { id: 14, title: "권시내" },
        { id: 15, title: "권한솔" },
        { id: 16, title: "유한별" },
        { id: 17, title: "이사랑" },
        { id: 18, title: "금초슬" },
        { id: 19, title: "채별나래" },
        { id: 20, title: "김가람" },
        { id: 21, title: "정시내" },
        { id: 22, title: "이하얀" },
        { id: 23, title: "진달래" },
        { id: 24, title: "고그리나" },
        { id: 25, title: "유아름" },
        { id: 26, title: "허단비" },
        { id: 27, title: "허봄비" },
        { id: 28, title: "허꽃비" },
        { id: 29, title: "옥찬돌" },
        { id: 30, title: "채운들" },
        { id: 31, title: "박꽃나위" },
        { id: 32, title: "박샘바위" },
        { id: 33, title: "한바다" },
        { id: 34, title: "정빛나" },
        { id: 35, title: "손모아" },
        { id: 36, title: "김별다미" },
        { id: 37, title: "김해마루" },
        { id: 38, title: "송빛다운" },
        { id: 39, title: "정샘터" },
        { id: 40, title: "김한솔" },
        { id: 41, title: "김슬기로" },
        { id: 42, title: "오다함" },
        { id: 43, title: "오다해" },
        { id: 44, title: "조든든" },
        { id: 45, title: "최소슬" },
        { id: 46, title: "정되난들" },
        { id: 47, title: "정샘이찬" },
        { id: 48, title: "홍해내리" },
        { id: 49, title: "이새롬" },
        { id: 50, title: "이푸름" },
        { id: 51, title: "이맑음" },
        { id: 52, title: "김고운" },
        { id: 53, title: "김하늘" },
        { id: 54, title: "최샘이나" },
        { id: 55, title: "정가득" },
        { id: 56, title: "이피어나" },
        { id: 57, title: "강미덥" },
        { id: 58, title: "배꽃하얀" },
        { id: 59, title: "배잎푸른" },
        { id: 60, title: "배한여름" },
        { id: 61, title: "해울" },
        { id: 62, title: "슬아" },
        { id: 63, title: "하랑" },
        { id: 64, title: "대솔" },
        { id: 65, title: "다예" },
        { id: 66, title: "초롱" },
        { id: 67, title: "누리큰빛" },
        { id: 68, title: "솔이" },
        { id: 69, title: "별보미" },
        { id: 70, title: "별보라" },
        { id: 71, title: "너나울" },
        { id: 72, title: "해듬" },
        { id: 73, title: "애솔" },
        { id: 74, title: "늘휘" },
        { id: 75, title: "솔빛나래" },
        { id: 76, title: "보늬" },
        { id: 77, title: "하늬" },
        { id: 78, title: "무늬" },
      ],
      total: 78,
      skip: 0,
      limit: 78,
    };

    return response.patients;
    // const response = await axios.get("https://dummyjson.com/products");
    // return response.data.products;
  } catch (error) {
    console.log(error);
  }
};
